# Generated by Django 3.0.3 on 2021-03-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='refer',
            field=models.CharField(choices=[('refer_1_star', '1_star'), ('refer_2_star', '2_star'), ('refer_3_star', '3_star'), ('refer_4_star', '4_star'), ('refer_5_star', '5_star')], default='refer_1_star', max_length=20),
        ),
    ]
