# Generated by Django 3.0.3 on 2021-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_auto_20210313_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='refer',
            field=models.CharField(choices=[('1_stars', '1_stars'), ('2_stars', '2_stars'), ('3_stars', '3_stars'), ('4_stars', '4_stars'), ('5_stars', '5_stars')], default='1_stars', max_length=20),
        ),
    ]
