# Generated by Django 3.1.2 on 2021-03-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_employer',
            new_name='is_user',
        ),
    ]
