# Generated by Django 3.0.3 on 2021-03-12 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cake', '0003_rate'),
        ('userprofile', '0002_auto_20210311_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to=settings.AUTH_USER_MODEL)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='cake.Rate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
